name: Triggered Demo Action

on:
  repository_dispatch:
    types: [actions-build-trigger]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}
      - run: |
          echo SHA ${{ github.event.client_payload.sha }}
          echo VERSION ${{ github.event.client_payload.version }}
          echo "<html><body>Latest version is ${{ github.event.client_payload.version }}!</body></html>" > index.html
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add index.html
          git commit -m "triggered new version ${{ github.event.client_payload.version }}"
          REMOTE="https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
          git push 
